### ISSUE TITLE
Mail kontrolü: GMail, Hotmail, vb.

### ISSUE THREAD

**Issue by G-Defender** [Kyzaghan/lanfear#1]
Mail kontrlü yapılabilir.

10 dakikalık mail ile üyelik açmaları engellemek amaçlı.

GMail ve outlook ile tek üye olunabilir.

Panel'den seçme olur hangilerine izin verilsin tarzında.

**Comment by Kyzaghan** [comment]
Parametrik olarak desteklendi, config/params.php adresinden ulaşılabilir.
