### ISSUE TITLE
VeriTabanı Eklenmesi

### ISSUE THREAD

**Issue by MembaCo** [Kyzaghan/lanfear#14]
Veritabanı Göremedim Eklenmedi mi Acaba !

**Comment by Kyzaghan** [comment]
Merhaba,
Kurulumdan sonra veritabanı ayarlarını yapınız, daha sonra aşağıda ki adresi çalıştırdığınızda veritabanı tabloları otomatik oluşturulacak.

siteadresi/web/seed/home
