### ISSUE TITLE
İstatistik olarak son 10 kayıt,giriş,oyun giriş olabilir.

### ISSUE THREAD

**Issue by G-Defender** [Kyzaghan/lanfear#3]
İstatistik servisinde,

1- Son üye olan 10 kişi.
2- Son giriş yapan 10 kişi.
3- Son oyun girişi yapan 10 kişi.

Olabilir.

**Comment by Kyzaghan** [comment]
son itme ile 2. madde son giriş yapan 10 kişi eklendi.

**Comment by Kyzaghan** [comment]
Tasarımsal nedenlerden dolayı
1- Son üye olan 5 kişi.
2- Son giriş yapan 5 kişi.

olarak değiştirildi.

**Comment by Kyzaghan** [comment]
Üç istekte tamamlanıp, istek kapatıldı.
