### ISSUE TITLE
Şifre değiştirme hakkında.

### ISSUE THREAD

**Issue by G-Defender** [Kyzaghan/lanfear#4]
Şifre değiştirmek isteyen kişi mail onaylı ise mail'e onaylama maili gönderilmeli.

Sms onaylı ise Telefon'a kod gelerek şifre değiştirilmeli.

**Comment by Kyzaghan** [comment]
Şifre değiştirme ekranı tanımlanıp, e-posta doğrulaması gerektiğinde mail ile çalışacak şekilde yapıldı. SMS ile ilgili öncelikle firma ve altyapı belirlenmesi gerektiği için istek şuanlık kapatılıyor.
