### ISSUE TITLE
Üye listesi ve sıralama.

### ISSUE THREAD

**Issue by G-Defender** [Kyzaghan/lanfear#7]
Üye listesi olmalı a 'dan z ye kadar harf seçmeli veya sıralama olarak.

Kullanıcı adı yazarak arama yapılabilir ve hem listede online oyuncular yeşil olarak gösterilir.

Online olmayanlar kırmızı olarak gösterilir.

**Comment by Kyzaghan** [comment]
Karakter listesi, istatistikler menüsü altına eklendi.
