### ISSUE TITLE
Oyuncuların paraları gözüksün.

### ISSUE THREAD

**Issue by G-Defender** [Kyzaghan/lanfear#9]
İstatislikte kimin nekadar parası varsa görünsün kesinlikle bence gol check farketmez oyunculara başlangıç için büyük güven verir

**Comment by Kyzaghan** [comment]
Oyuncunun para bilgisine nasıl ulaşabiliriz. src.gold ?

**Comment by Kyzaghan** [comment]
İstatistik desteklendi.
